version: "3.9"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: django
      MYSQL_ROOT_PASSWORD: password

  web:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - .:/template-django-flutter
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_NAME: django
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    tty: true